### ISSUE TITLE
Checklist before merging to `master`

### ISSUE THREAD

**Issue by vincetran96** [coinForRich/coin-for-rich#19]
- [x] Merge `dockerize` into `dev`
- [x] Screenshots
- [x] Write more unit tests
- [x] Document more on APIs
